### ISSUE TITLE
How to make an item do something?

### ISSUE THREAD

**Issue by Hedronmx** [gagdiez/personal_godot#3]
Should I add a function on each item with the logic? Or how can I implement logic to each item in the inventory?

**Comment by gagdiez** [comment]
Indeed. On each object, you need to:

1) Extend the interactive class: "extend Interactive"
2) Add a main_action (for example: ACTIONS.use, ACTIONS.take, or any action defined in Actions.gd)
3) Add the corresponding action for the "main_action". For example, if the main_action is ACTIONS.take, you need to define the function "func take(who)". If the main_action is ACTIONS.use, you need to defined "func use(who)"

The function will be called when someone clicks on the object, and the parameter "who" will be the character that is being used.

I have created a new repo, with a minimal example: https://github.com/gagdiez/PAC-gd. Such repo will soon point to the plugin's website, and will include the documentation.

If you have any further questions let me know.

Saludos!

**Comment by Hedronmx** [comment]
What if I want a custom action? For example a key that opens a door?

**Comment by gagdiez** [comment]
You could add a variable in the door, saying that it's locked, which changes after the player uses the key on it:

```
# Door NODE
func _ready():
  var unlocked = false  # The Door start locked

func open(who):
  if unlocked:
    <<code when the door is locked>>
  else:
    who.say("It is locked")

func use_item(who, what):
  # Function called when I use an item on the door
  if what == $KEY_NODE:
    <<code to approach door, see the minimal examples in the other repo>>
    who.say("The door is unlocked now")
    self.unlocked = true  # The door is now unlocked
 else:
    who.say("I cannot use that there")
```

**Comment by Hedronmx** [comment]
I see!! Now I understand it! This is really good, thank you!!
