### ISSUE TITLE
How to use the talk to action?

### ISSUE THREAD

**Issue by Hedronmx** [gagdiez/personal_godot#4]
I dont know what parameters should I send to the talk to function. I want to create an NPC, should I duplicate the player node?

**Comment by gagdiez** [comment]
The function "talk_to" receives the parameter "who". "who" is the person that is trying to talk with me, so, to make an NPC you can do:

```
# My_NPC.gd
extends Player

func talk_to(who):
  # The parameter "who" is the Player that IS TALKING TO ME
  print(who.name + " is talking with me")
  cut_scene_conversation.play()
```

So far this will work only once, since you found a bug in the cut_scene code (thanks!!!)

I will fix it now.

**Comment by Hedronmx** [comment]
Awesome! I kind of did it in reverse where who is the player and then the npc triggers the cutscene. Ill close this now
