### ISSUE TITLE
How to repeat a cutscen?

### ISSUE THREAD

**Issue by Hedronmx** [gagdiez/personal_godot#5]
How can I repeat a cutscene... If I call the play function after the cutscene is done, it doesnt play.

**Comment by gagdiez** [comment]
Indeed, this is a bug, I will work on it now to solve it ASAP.

**Comment by Hedronmx** [comment]
Awesome! Hopefully it will be an easy fix! I have already modified a lot of the project. Thank you so much for your time and effort

**Comment by gagdiez** [comment]
Should be fixed in the current commit. Please "pull" from the main branch the update. If any other problem arises let me know.

**Comment by Hedronmx** [comment]
Works great!
